# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(default=None, max_length=5, primary_key=True, serialize=False)),
                ('capacity', models.CharField(default='2', max_length=5)),
                ('vacancy', models.CharField(default='2', max_length=5)),
                ('rent', models.CharField(default='6000', max_length=5)),
                ('additional_charges', models.BooleanField(default=False)),
                ('need_maintenance', models.BooleanField(default=False)),
                ('repairs', models.CharField(default='0', max_length=8)),
            ],
        ),
    ]
