# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1 Part Payment', '1 Part Payment'), ('2 Part Payment', '2 Part Payment'), ('Monthly payment', 'Monthly payment')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
