# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype',
            new_name='roomType',
        ),
    ]
