# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20170915_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='need_maintenance',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='repairs',
        ),
        migrations.AlterField(
            model_name='room',
            name='additional_charges',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.CharField(max_length=5),
        ),
    ]
