# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20171018_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rent',
        ),
    ]
