# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20170915_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='need_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.CharField(default='6000', max_length=5),
        ),
        migrations.AddField(
            model_name='room',
            name='repairs',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='additional_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(default='2', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='vacancy',
            field=models.CharField(default='2', max_length=5),
        ),
    ]
