# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import smartadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('adhaar', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address_l1', models.CharField(max_length=100)),
                ('address_l2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=6)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('adminid', models.CharField(default=smartadmin.models.increment_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
