# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 17:03
from __future__ import unicode_literals

import Inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('item_id', models.CharField(default=Inventory.models.item_id, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
