# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 17:05
from __future__ import unicode_literals

import Inventory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20180307_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_log_id', models.CharField(default=Inventory.models.inventory_id, max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('quantity', models.CharField(max_length=4)),
                ('unit', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.InventoryItems')),
            ],
        ),
    ]
