# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='itemid',
            new_name='item',
        ),
    ]
