# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20180308_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='unit',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
