# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_inventory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(max_length=6),
        ),
    ]
