# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='particulars',
            field=models.CharField(default='fees', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction_details',
            name='payment_mode',
            field=models.CharField(max_length=20),
        ),
    ]
