# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171022_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
