# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20180302_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='cheque_dd_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
