# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.FloatField(max_length=20)),
                ('security_money', models.FloatField(max_length=5)),
                ('fine', models.FloatField(max_length=5)),
            ],
        ),
    ]
