# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='id',
        ),
        migrations.AddField(
            model_name='fees',
            name='room_type',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
