# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0002_auto_20170918_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fees', models.FloatField(max_length=5)),
                ('Security_money', models.FloatField(max_length=5)),
                ('Fine', models.FloatField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='dues',
            name='sid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
