# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0002_auto_20171018_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='parts_per_year',
            field=models.IntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
