# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0003_fees_parts_per_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='parts_per_year',
            field=models.IntegerField(),
        ),
    ]
