# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0003_auto_20170920_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dues',
            old_name='roomfees',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='dues',
            name='messfees',
        ),
    ]
