# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0005_auto_20170921_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='Fees',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='fees',
            old_name='Fine',
            new_name='fine',
        ),
        migrations.RenameField(
            model_name='fees',
            old_name='Security_money',
            new_name='security_money',
        ),
    ]
