# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0006_auto_20170922_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees',
            field=models.FloatField(max_length=10),
        ),
    ]
