# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0007_auto_20170923_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
