# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0009_auto_20170923_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dues',
        ),
    ]
