# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import payfees.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentinfo_password'),
        ('payfees', '0010_delete_dues'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('transaction_id', models.CharField(default=payfees.models.increment_transaction_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('credit', models.FloatField(max_length=5)),
                ('debit', models.FloatField(max_length=5)),
                ('remarks', models.CharField(max_length=400)),
                ('balance', models.FloatField(max_length=5)),
                ('transaction_type', models.CharField(max_length=10)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentinfo')),
            ],
        ),
    ]
