# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0011_transactiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='transaction_mode',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
