# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0012_transactiondetails_transaction_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='credit',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='debit',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
