# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0013_auto_20170928_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='credit',
            field=models.FloatField(blank=True, default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='debit',
            field=models.FloatField(blank=True, default=0, max_length=5),
            preserve_default=False,
        ),
    ]
