# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0014_auto_20170928_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='credit',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='debit',
            field=models.FloatField(max_length=5),
        ),
    ]
