# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payfees', '0012_transactiondetails_transaction_type'),
        ('payfees', '0015_auto_20170928_1435'),
    ]

    operations = [
    ]
