# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('sid', models.CharField(default=student.models.increment_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('adhaar', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_mobile', models.CharField(max_length=10)),
                ('address_l1', models.CharField(max_length=100)),
                ('address_l2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_mobile', models.CharField(max_length=10)),
                ('institution_name', models.CharField(max_length=30)),
                ('hod_name', models.CharField(max_length=30)),
                ('hod_mobile', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(max_length=5)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.Room')),
            ],
        ),
    ]
