# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170923_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
    ]
