# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('userid', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
