# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170930_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='session_key',
            new_name='sessionkey',
        ),
    ]
