# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20170930_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.CharField(default=student.models.message_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('type_of_message', models.CharField(max_length=20)),
                ('body_of_message', models.CharField(max_length=200)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentinfo')),
            ],
        ),
    ]
