# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='sessionkey',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
