# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20171008_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='sessionkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
