# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20171008_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.CharField(default=student.models.notice_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('type_of_notice', models.CharField(max_length=20)),
                ('body_of_notice', models.CharField(max_length=200)),
            ],
        ),
    ]
