# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='hod_mobile',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='hod_name',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='blood_grp',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='room_allotment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_mobile',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
