# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
