# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20171012_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
