# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentinfo_active'),
        ('student', '0013_auto_20171012_1153'),
    ]

    operations = [
    ]
