# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20171014_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('msg_id', models.CharField(default=student.models.msg_id, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_email', models.CharField(max_length=30)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('body_of_message', models.CharField(max_length=200)),
            ],
        ),
    ]
