# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentinfo_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='next_installment',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
