# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_studentinfo_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 16, 11, 54, 363017, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
