# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_studentinfo_next_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='next_installment',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
