# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_studentinfo_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='hod_mobile',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='hod_name',
        ),
    ]
