# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20180415_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='next_installment',
            field=models.FloatField(max_length=6, null=True),
        ),
    ]
