# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20171013_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateTimeField(default='NA'),
        ),
    ]
