# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_studentinfo_date_of_birth'),
        ('student', '0014_merge_20171012_2105'),
    ]

    operations = [
    ]
