# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170930_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
